export const homeFeed = [
    {
        feedId : 1,
        userId : 1, 
        userName : "Nag Sumanth",
        isFollowing : false,
        itemId : 1,
        categoryId : 1,
        categoryName : "Shoes",
        contextId : 1, 
        contextName : "10hrs+ per week running",
        productId : 1,
        productName : "Adidas Speed Pro Max",
        image : "https://petapixel.com/assets/uploads/2017/03/product1.jpeg",
        comment : "This is the comment about the recommendation that i will show fasfa and dfasdf fadsfas fasfsa dfsa fsaf safsaf sa fsa",
        like : true,
        dislike : null,
        buyButtonLink : "https://www.amazon.com",
        buyButtonMessage : "We will redirect you to amazon"
    },
    {
        feedId : 2,
        userId : 2, 
        userName : "Sagi Avinash Varma Krishna Ira ",
        isFollowing : false,
        itemId : 2,
        categoryId : 2,
        categoryName : "Mobile",
        contextId : 1, 
        contextName : "10 Hrs+ per day",
        productId : 1,
        productName : "Apple Iphone 13",
        image : "https://petapixel.com/assets/uploads/2017/03/product1.jpeg",
        comment : "Iphone is the best phone that came out till now . Bit expensive but perfecty awersome how fasfa and dfasdf fadsfas fasfsa dfsa fsaf safsaf sa fsa",
        like : true,
        dislike : null,
        buyButtonLink : "https://www.amazon.com",
        buyButtonMessage : "We will redirect you to amazon"
    }
]