import faker from 'faker';

export const categories = [
  {
    categoryId: 1,
    categoryName: 'Laptops',
    categoryImage:
      'https://www.cnet.com/a/img/resize/3599cd5e2e3a7423a49de0da1a9de2a84e8e3d16/hub/2018/02/13/517fda12-de2a-4c3f-bee5-05daaf870537/01laptops-with-longest-battery-life-2018-feb.jpg?auto=webp&width=1092',
    noOfRecommendations: 10,
    isFollowing: true,
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
  {
    categoryId: faker.datatype.uuid(),
    categoryName: faker.commerce.department(),
    categoryImage: faker.image.imageUrl(),
    noOfRecommendations: faker.datatype.number(),
    isFollowing: faker.datatype.boolean(),
    contextIfAvailable: '',
  },
];
